version: '2'

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/data'
    environment:
      - CASSANDRA_SEEDS=cassandra
volumes:
  cassandra_data:
    driver: local
